accounts/urls.py
from django.contrib import admin
from django.urls import re_path
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from . import views as accounts_views

app_name = 'accounts'
urlpatterns = [
    re_path(r'^signup/$', accounts_views.signup, name='signup'),
    re_path(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'^reset/$', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset.html',
        email_template_name='accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt', success_url='/accounts/reset/done/'
    ), name='password_reset'),
    re_path(r'^reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
            name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(
                template_name='accounts/password_reset_confirm.html', success_url='/accounts/reset/complete/'),
            name='password_reset_confirm'),
    re_path(r'^reset/complete/$', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    re_path(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html',
                                                                           success_url='/accounts/settings/password/done/'), name='password_change'),
    re_path(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
            name='password_change_done'),
]

tdl/urls.py
from django.urls import re_path
from . import views

app_name = 'tdl'
urlpatterns = [
    re_path(r'^$', views.index.as_view(), name='index'),
    re_path(r'^index/xhrval(?P<show>[tf]{1})/$', views.show_hide, name='show_hide'),
    re_path(r'^index/xhr/$', views.show_hide_getval, name='show_hide_getval'),
    re_path(r'^task_done/(?P<task_id>\d+)/$', views.task_done, name='task_done'),
    re_path(r'^task_undone/(?P<task_id>\d+)/$', views.task_undone, name='task_undone'),
    re_path(r'^task_edit/(?P<task_id>\d+)/$', views.task_edit.as_view(), name='task_edit'),
    re_path(r'^task_delete/(?P<task_id>\d+)/$', views.task_delete.as_view(), name='task_delete'),
    re_path(r'^new/$', views.new_task.as_view(), name='new_task'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from captcha.fields import CaptchaField


class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())
    captcha = CaptchaField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.shortcuts import render, redirect
from .forms import SignUpForm


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('tdl:index')
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})

accounts/templates/accounts/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'accounts/css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'home' %}"><img border="0" alt="To Do List" src="{% static 'img/logo1a.png' %}" width="150" height="150" ></a>
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}ToDoList Login{% endblock %}

{% block content  %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Log in</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            {% include 'includes/form.html' %}
            <button id="submit_button" type="submit" class="btn btn-primary btn-block">Log in</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          New to ToDoList? <a href="{% url 'accounts:signup' %}">Sign up</a>
        </div>
      </div>
      <div class="text-center py-2">
        <small>
          <a href="{% url 'accounts:password_reset' %}" style="background-color:rgb(0, 51, 204); color:rgb(153, 102, 255);" class="text-muted" > &nbsp; Forgot your password? &nbsp;</a>
        </small>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends 'base.html' %}

{% block title %}Change password{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Change password</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success" id="submit_button">Change password</button>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends 'base.html' %}

{% block title %}Change password successful{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'accounts:password_change' %}" id="change_pasword_id">Change password</a></li>
  <li class="breadcrumb-item active">Success</li>
{% endblock %}

{% block content %}
  <div class="alert alert-success" role="alert">
    <strong>Success!</strong> Your password has been changed!
  </div>
  <a href="{% url 'home' %}" class="btn btn-secondary" id="return_to_home_id">Return to home page</a>
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Enter your email address and we will send you a link to reset your password.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block" id="submit_button">Send password reset email</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Password changed!{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Password changed!</h3>
          <div class="alert alert-success" role="alert">
            You have successfully changed your password! You may now proceed to log in.
          </div>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-block" id="id_login_link">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}
  {% if validlink %}
    Change password for {{ form.user.username }}
  {% else %}
    Reset your password
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">Change password for @{{ form.user.username }}</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-success btn-block" id="submit_button">Change password</button>
            </form>
          {% else %}
            <h3 class="card-title">Reset your password</h3>
            <div class="alert alert-danger" role="alert">
              It looks like you clicked on an invalid password reset link. Please try again.
            </div>
            <a href="{% url 'accounts:password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Check your email for a link to reset your password. If it will not appear within a few minutes, check your spam folder.</p>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-block" id="return_to_login_id">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
Hi there,

There is asked for a password reset for the email address {{ email }}.

Follow the link below:
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

If you forgot your ToDoList username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The ToDoList

accounts/templates/accounts/signup.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Sign up to ToDoList{% endblock %}

{% block content %}
    <div class="row justify-content-center">
      <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Sign up</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button id ="submit_button" type="submit" class="btn btn-primary btn-block">Create an account</button>
            </form>
          </div>
          <div class="card-footer text-muted text-center">
            Already have an account? <a href="{% url 'accounts:login' %}">Log in</a>
          </div>
        </div>
      </div>
    </div>
{% endblock %}