tdl/urls.py
from django.urls import re_path
from . import views

app_name = 'tdl'
urlpatterns = [
    re_path(r'^$', views.index.as_view(), name='index'),
    re_path(r'^index/xhrval(?P<show>[tf]{1})/$', views.show_hide, name='show_hide'),
    re_path(r'^index/xhr/$', views.show_hide_getval, name='show_hide_getval'),
    re_path(r'^task_done/(?P<task_id>\d+)/$', views.task_done, name='task_done'),
    re_path(r'^task_undone/(?P<task_id>\d+)/$', views.task_undone, name='task_undone'),
    re_path(r'^task_edit/(?P<task_id>\d+)/$', views.task_edit.as_view(), name='task_edit'),
    re_path(r'^task_delete/(?P<task_id>\d+)/$', views.task_delete.as_view(), name='task_delete'),
    re_path(r'^new/$', views.new_task.as_view(), name='new_task'),
]

tdl/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Task(models.Model):
    name = models.CharField(max_length=40)
    description = models.CharField(max_length=4000)
    issued_by = models.ForeignKey(User, related_name='issued', on_delete=models.CASCADE)
    done = models.BooleanField(default=False)
    done_by = models.ForeignKey(User, related_name='+', null=True,
                                blank=True, on_delete=models.SET_NULL)


class Preferences(models.Model):
    user = models.OneToOneField(User, related_name='+', on_delete=models.CASCADE)
    show_all = models.BooleanField(default=False)


@receiver(post_save, sender=User)
def create_user_preferences(sender, instance, created, **kwargs):
    if created:
        Preferences.objects.create(user=instance)

tdl/forms.py
from django import forms
from .models import Task


class NewTaskForm(forms.ModelForm):
    name = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write here a short task name', 'size': 40, 'rows': 1}),
                           max_length=40, help_text='The Maximium Length is 40'
                           )
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write here the new task.', 'size': 4000}), max_length=4000,
                                  help_text='The Maximium Length is 4000'
                                  )

    class Meta:
        model = Task
        fields = ['name', 'description', ]

tdl/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.http import HttpResponse, response
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Task, Preferences
from .forms import NewTaskForm


class index(LoginRequiredMixin, ListView):
    model = Task
    template_name = 'tdl/index.html'
    context_object_name = 'tasks'
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.order_by('pk')


@login_required
def show_hide(request, show):
    user = request.user.pk
    preferences = get_object_or_404(Preferences, user=user)
    preferences.show_all = (show == "t")
    preferences.save()
    return HttpResponse(preferences.show_all)


@login_required
def show_hide_getval(request):
    user = request.user
    preferences, _ = Preferences.objects.get_or_create(
        user=user, defaults={'user': user, 'show_all': False})
    return HttpResponse(preferences.show_all)


class new_task(LoginRequiredMixin, CreateView):
    model = Task
    form_class = NewTaskForm
    template_name = 'tdl/new_task.html'
    context_object_name = 'form'

    def form_valid(self, form):
        task = form.save(commit=False)
        task.issued_by = self.request.user
        task.save()
        return redirect('tdl:index')


class task_edit(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = NewTaskForm
    template_name = 'tdl/edit.html'
    context_object_name = 'form'
    pk_url_kwarg = 'task_id'
    success_url = reverse_lazy('tdl:index')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(issued_by=self.request.user)


class task_delete(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = reverse_lazy('tdl:index')
    pk_url_kwarg = 'task_id'
    template_name = 'tdl/delete_confirm.html'
    context_object_name = 'task'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(issued_by=self.request.user)


@login_required
def task_done(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    task.done = True
    task.done_by = request.user
    task.save()
    tasks = Task.objects.all()
    return redirect('tdl:index')


@login_required
def task_undone(request, task_id):
    task = get_object_or_404(Task, pk=task_id, issued_by=request.user)
    task.done = False
    task.save()
    tasks = Task.objects.all()
    return redirect('tdl:index')

tdl/templates/tdl/delete_confirm.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Delete the Task{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'tdl:index' %}">Tasks</a></li>
  <li class="breadcrumb-item active">Delete Task</li>
{% endblock %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ task.name }}"?</p>
    <button type="submit" class="btn btn-success" id="id_deleteTask">Confirm</button> 
  </form>
{% endblock %}

tdl/templates/tdl/edit.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Edit the Task{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'tdl:index' %}">Tasks</a></li>
  <li class="breadcrumb-item active">Edit Task</li>
{% endblock %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success" id="id_updateTask">Update</button>
  </form>
{% endblock %}

tdl/templates/tdl/index.html
{% extends 'base.html' %}
{% load static %}
{% block breadcrumb %}
{% endblock %}

{% block content %}
    <div class="mb-4">
      <a href="{% url 'tdl:new_task' %}" class="btn btn-primary" id="id_newTask">New Task</a>
      <button id="taskFilter" class="btn btn-primary" type="button" style="float:right" value="" onclick="ShowHideDoneTasks()"></button>
    </div>
    <table class="table">
      <thead class="thead-inverse">
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Issued by</th>
          <th>Done by</th>
        </tr>
      </thead>
      <tbody>
        {% for task in tasks %}
            <tr class={% if task.done %} "doneclass" style="background-color:rgb(214, 214, 214);" {% else %} "undoneclass" style="background-color:rgb(204, 251, 214);" {% endif %} >
              <td> {{ task.name }}
                {% if user == task.issued_by %}
                  <a href="{% url 'tdl:task_edit' task.pk %}" class="btn btn-primary btn-sm"
                    role="button"> <img alt="Edit" src="{% static 'tdl/img/edit-48.png' %}" width="24" height="24" > </a>
                {% endif %}
              </td>
              <td> {{ task.description }} </td>
              <td class="align-middle"> {{ task.issued_by }}
                {% if user == task.issued_by %}
                  <a href="{% url 'tdl:task_delete' task.pk %}" class="btn btn-primary btn-sm"
                    role="button"> <img alt="Delete?" src="{% static 'tdl/img/trash-48.png' %}" width="24" height="24" > </a>
                {% endif %}
              </td>
              <td class="align-middle">
                {% if task.done %}
                  {{ task.done_by }}
                  {% if user == task.issued_by %}
                    <a href="{% url 'tdl:task_undone' task.pk %}" class="btn btn-primary btn-sm" name="done_undone"
                     role="button"> <img alt="Undone?" src="{% static 'tdl/img/undo-48.png' %}" width="24" height="24" > </a>
                  {% endif %}
                {% else %}
                  <a href="{% url 'tdl:task_done' task.pk %}" class="btn btn-primary btn-sm" name="done_undone"
                   role="button"> Done? </a>
                  {% if task.done_by %}
                     <small>{{ task.done_by }} has worked last</small>
                  {% endif %}
                {% endif %}
              </td>
            </tr>
          {% endfor %}
      </tbody>
    </table>
    {% if is_paginated %}
      <nav aria-label="Tasks pagination" class="mb-4">
        <ul class="pagination">
          {% if page_obj.number > 1 %}
            <li class="page-item">
              <a class="page-link" href="?page=1">First</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">First</span>
            </li>
          {% endif %}

          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">Previous</span>
            </li>
          {% endif %}

          {% for page_num in paginator.page_range %}
            {% if page_obj.number == page_num %}
              <li class="page-item active">
                <span class="page-link">
                  {{ page_num }}
                  <span class="sr-only">(current)</span>
                </span>
              </li>
            {% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3' %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
              </li>
            {% elif page_num == page_obj.number|add:'-4' or page_num < page_obj.number|add:'4' %}
              <li class="page-item disabled">
                <span class="page-link"> ... </span>
              </li>
            {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">Next</span>
            </li>
          {% endif %}

          {% if page_obj.number != paginator.num_pages %}
            <li class="page-item">
              <a class="page-link" href="?page={{ paginator.num_pages }}">Last</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">Last</span>
            </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
{% endblock %}
{% block scripts %}
    <script src="{% static 'tdl/js/filter.js'%}"></script>
{% endblock %}

tdl/templates/tdl/new_task.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Issue a New Task{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'tdl:index' %}">Tasks</a></li>
  <li class="breadcrumb-item active">New Task</li>
{% endblock %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success" id="id_postNewTask">Post</button>
  </form>
{% endblock %}