accounts/urls.py
from django.contrib import admin
from django.urls import re_path
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from . import views as accounts_views

app_name = 'accounts'
urlpatterns = [
    re_path(r'^signup/$', accounts_views.signup, name='signup'),
    re_path(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'^reset/$', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset.html',
        email_template_name='accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt', success_url='/accounts/reset/done/'
    ), name='password_reset'),
    re_path(r'^reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
            name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(
                template_name='accounts/password_reset_confirm.html', success_url='/accounts/reset/complete/'),
            name='password_reset_confirm'),
    re_path(r'^reset/complete/$', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    re_path(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html',
                                                                           success_url='/accounts/settings/password/done/'), name='password_change'),
    re_path(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
            name='password_change_done'),
]

tdl/urls.py
from django.urls import re_path
from . import views

app_name = 'tdl'
urlpatterns = [
    re_path(r'^$', views.index.as_view(), name='index'),
    re_path(r'^index/xhrval(?P<show>[tf]{1})/$', views.show_hide, name='show_hide'),
    re_path(r'^index/xhr/$', views.show_hide_getval, name='show_hide_getval'),
    re_path(r'^task_done/(?P<task_id>\d+)/$', views.task_done, name='task_done'),
    re_path(r'^task_undone/(?P<task_id>\d+)/$', views.task_undone, name='task_undone'),
    re_path(r'^task_edit/(?P<task_id>\d+)/$', views.task_edit.as_view(), name='task_edit'),
    re_path(r'^task_delete/(?P<task_id>\d+)/$', views.task_delete.as_view(), name='task_delete'),
    re_path(r'^new/$', views.new_task.as_view(), name='new_task'),
]

templates/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <meta charset="utf-8">
    <title>{% block title %}To Do List{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block stylesheet %}{% endblock %}
  </head>
  <body>
    {% block body %}
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <img border="0" alt="To Do List" src="{% static 'img/logo1a.png' %}" width="100" height="100" id="logo_image_id">
          <div class="collapse navbar-collapse" id="mainMenu">
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ user.username }}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                  <a class="dropdown-item" href="{% url 'accounts:password_change' %}" id="change_password_id">Change password</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'accounts:logout' %}" id="logout_id">Log out</a>
                </div>
              </li>
            </ul>
            {% else %}
              <form class="form-inline ml-auto">
                <a href="{% url 'accounts:login' %}" class="btn btn-outline-secondary">Log in</a>
                <a href="{% url 'accounts:signup' %}" class="btn btn-primary ml-2">Sign up</a>
              </form>
            {% endif %}
          </div>
        </div>
      </nav>
      <div class="container">
        <ol class="breadcrumb my-4">
          {% block breadcrumb %}
          {% endblock %}
        </ol>
        {% block content %}
        {% endblock %}
      </div>
    {% endblock body %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>